In [6]:
import numpy as np
print(np.__version__)

2.0.0


In [18]:
arr = np.array([1, 2, 3, 4, 5]) 
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr.shape)
print(arr_2.shape)  
print(arr_3.size)  

(5,)
(2, 3)
12


In [19]:
a = np.array([1, 2, 3, 4, 5])
print(a.dtype) 

b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  

c = np.array([1+2j, 3+4j])
print(c.dtype)  

d = np.array([True, False, True])
print(d.dtype)  

int64
float64
complex128
bool


In [23]:
ar = np.array([1, 2, 3, 4, 5], dtype=np.float64)

print(ar)

b = np.array((10, 20, 30))
print(b) 

[1. 2. 3. 4. 5.]
[10 20 30]


In [24]:
c = [1, 2, 3, 4, 5]
a = np.asarray(c)
print(a)  

[1 2 3 4 5]


In [25]:
d = (10, 20, 30)
b = np.asarray(d)
print(b)  

[10 20 30]


In [26]:
a = np.ones(5)
print(a)  

[1. 1. 1. 1. 1.]


In [27]:
b = np.ones((3, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
a = np.zeros(5)
print(a)  

[0. 0. 0. 0. 0.]


In [29]:
b = np.zeros((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# Create an uninitialized 1D array
a = np.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [31]:
# Create an uninitialized 2D array with shape (2, 3)
b = np.empty((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# Create a sequence from 0 to 9
a = np.arange(10)
print(a)  

[0 1 2 3 4 5 6 7 8 9]


In [33]:
b = np.arange(2, 11, 2)
print(b)  

[ 2  4  6  8 10]


In [34]:
# Create an array with 5 evenly spaced values between 0 and 1
a = np.linspace(0, 1, 5)
print(a) 

[0.   0.25 0.5  0.75 1.  ]


In [35]:
# Create an array with 9 evenly spaced values between 0 and 10
b = np.linspace(0, 10, 9)
print(b)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [36]:
# Create a 2x2 identity matrix
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [37]:
# Create a 3x3 identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = b - a
print(c) 

[3 3 3]


In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print(c)  

[ 4 10 18]


In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = b / a
print(c)  

[4.  2.5 2. ]


In [42]:
a = np.array([1, 2, 3])

b = a * 2
print(b)  

c = a / 2
print(c) 

[2 4 6]
[0.5 1.  1.5]


In [43]:
a = np.array([1, 4, 9])

b = np.sqrt(a)
print(b) 

[1. 2. 3.]


In [44]:
a = np.array([1, 2, 3])

b = np.exp(a)
print(b) 

[ 2.71828183  7.3890561  20.08553692]


In [45]:
# 1D array and scalar
a = np.array([1, 2, 3])
b = 2
c = a + b  
print(c)

[3 4 5]


In [46]:
# 2D array and 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = a + b
print(c)

[[11 22 33]
 [14 25 36]]


In [47]:
# Different shapes: (2, 3) and (3, 2)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = a + b  

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [48]:
import time

# Create large arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)

# Element-wise operations in NumPy
start = time.time()
c = a + b
end = time.time()
print(f"NumPy element-wise addition took: {end - start:.6f} seconds")

# Element-wise operations in Python lists
start = time.time()
x = [i for i in range(10000000)]
y = [i for i in range(10000000)]
z = [x[i] + y[i] for i in range(10000000)]
end = time.time()
print(f"Python list element-wise addition took: {end - start:.6f} seconds")

NumPy element-wise addition took: 0.029789 seconds
Python list element-wise addition took: 3.980193 seconds


In [49]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a[0])  
print(a[3])  

1
4


In [50]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 0])  
print(b[2, 1])  

1
8


In [51]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(a[indices])

[1 3 5]


In [52]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([0, 2])
print(b[rows, cols])

[1 9]


In [53]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])

[4 5]


In [54]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[b > 5]) 

[6 7 8 9]


In [55]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])  
print(a[:4])   
print(a[5:])   
print(a[::2])
print(a[::-1]) 

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [56]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0:2, 0:2])  
print(b[:, 1])      
print(b[1:, :2])   

[[1 2]
 [4 5]]
[2 5 8]
[[4 5]
 [7 8]]


In [57]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::3])  
print(a[::-2])

[1 4 7]
[9 7 5 3 1]


In [58]:
a = np.array([1, 2, 3, 4, 5])
a[1:4] = 10
print(a)

[ 1 10 10 10  5]


In [59]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)  

# Reshape to a 2D array
b = a.reshape(2, 3)
print(b)

# Reshape to a 3D array
c = a.reshape(2, 1, 3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [60]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)  

# Flatten the array
b = a.ravel()
print(b)  

(2, 3)
[1 2 3 4 5 6]


In [64]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along a new axis (stacking)
c = np.stack((a, b))
print(c)

# Concatenate along an existing axis (horizontal)
d = np.concatenate((a, b), axis=None)
print(d)  

# Concatenate along an existing axis (vertical)
e = np.array([[1, 2], [3, 4]])
f = np.array([[5, 6], [7, 8]])
g = np.concatenate((e, f), axis=0)
print(g)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [65]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [68]:
# Create a 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Split the array horizontally into 2 sub-arrays
left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)

Horizontal split:
Left sub-array:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Right sub-array:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [71]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)  

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [72]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b) 

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [73]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b) 

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)